[package]
name = "andrias-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
default = []
standard = ["dep:andrias-standard", "andrias-standard/standard"]

[dependencies]
andrias-standard = { workspace = true, default-features = false, optional = true }
andrias-graph.workspace = true
andrias-kernel.workspace = true
andrias-plan.workspace = true
andrias-state.workspace = true
andrias-types.workspace = true

[dev-dependencies]
anyhow = { workspace = true, default-features = false, features = ["std"] }
serde_json = { workspace = true, default-features = false, features = ["std"] }
tokio = { workspace = true, default-features = false, features = ["rt", "sync", "macros"] }
