//! Value provenance / taint (§21.5) — the AI-injection structural defense.
//!
//! The threat that distinguishes an AI kernel from an ordinary capability
//! system is not malicious *code* but a model manipulated by malicious
//! *content* (a web page, a chat message, a tool result). Ordinary capability
//! models have only spatial attenuation (child ⊆ parent); they have no
//! *contextual* attenuation, so an injected Plan inherits the Process's full
//! Grant set. Taint is the first of the two structural defenses (§21.5): every
//! value carries the lineage of where its data came from, and that lineage
//! propagates input→output through every Operation. Policies then decide *by
//! structure* — not by fragile hash matching — e.g. an outbound Operation whose
//! input lineage touched a `Protected` source is denied.
//!
//! Honest boundary (§21.5): taint is a conservative over-approximation (it can
//! false-positive) and it does not stop a model that *understands then
//! paraphrases* a secret. But it moves the line from "can a hash match?" to "did
//! this value's lineage ever touch a protected source?" — a structural fact a
//! paraphrase cannot erase.

use crate::path::Path;
use serde::{Deserialize, Serialize};
use smol_str::SmolStr;

/// Where a value's data originated. The lineage label that propagates with the
/// value through every Operation (§21.5).
#[derive(Clone, Debug, Eq, Hash, PartialEq, Ord, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaintSource {
    /// Hard-coded in the Program by its author. Trusted.
    AuthorConstant,
    /// Generated by a model (an inference Operation's output).
    ModelOutput,
    /// An inbound event — chat message, webhook, platform event. Stamped by the
    /// daemon at the Source-ingest boundary (§16.3.3): `source_extension_id`
    /// names the extension that produced it, `event_stream` the stream within
    /// that extension. This is the authoritative provenance an extension's
    /// self-reported metadata cannot clear or forge (§16.3.3).
    Inbound {
        source_extension_id: SmolStr,
        event_stream: SmolStr,
    },
    /// A fetch result or external tool output, tagged by host.
    Fetched { host: SmolStr },
    /// Read from a protected source (`state://vault/*`, private, health).
    Protected { path: Path },
}

impl TaintSource {
    /// Whether this source is protected (vault / private / health). Outbound
    /// flow of protected data is structurally denied (§21.5).
    pub fn is_protected(&self) -> bool {
        matches!(self, TaintSource::Protected { .. })
    }

    /// Whether this source is untrusted content (model / inbound / fetched) —
    /// the lineage that makes a value a memory-poisoning risk (§21.5).
    pub fn is_untrusted_content(&self) -> bool {
        matches!(
            self,
            TaintSource::ModelOutput | TaintSource::Inbound { .. } | TaintSource::Fetched { .. }
        )
    }
}

/// The set of sources a value's lineage has touched. Empty = pristine
/// (equivalent to a pure author constant with nothing mixed in). The set is the
/// union of every input's taint that flowed into producing this value.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct TaintSet {
    sources: Vec<TaintSource>,
}

impl TaintSet {
    /// A pristine (empty) taint set.
    pub fn pristine() -> Self {
        Self {
            sources: Vec::new(),
        }
    }

    /// A taint set with a single source.
    pub fn of(source: TaintSource) -> Self {
        Self {
            sources: vec![source],
        }
    }

    /// Author-constant taint (trusted program literal).
    pub fn author() -> Self {
        Self::of(TaintSource::AuthorConstant)
    }

    /// Add a source (idempotent — duplicates are coalesced).
    pub fn add(&mut self, source: TaintSource) {
        if !self.sources.contains(&source) {
            self.sources.push(source);
        }
    }

    /// Union another set into this one (the propagation operator: output taint
    /// = union of all input taints, §21.5).
    pub fn union(&mut self, other: &TaintSet) {
        for s in &other.sources {
            self.add(s.clone());
        }
    }

    /// Merge two sets into a new one.
    pub fn merged(mut self, other: &TaintSet) -> Self {
        self.union(other);
        self
    }

    /// Whether the lineage touched any protected source (outbound gate, §21.5).
    pub fn has_protected(&self) -> bool {
        self.sources.iter().any(TaintSource::is_protected)
    }

    /// Whether the lineage touched untrusted content (memory-poison gate).
    pub fn has_untrusted_content(&self) -> bool {
        self.sources.iter().any(TaintSource::is_untrusted_content)
    }

    /// Whether the set is pristine (no recorded sources).
    pub fn is_pristine(&self) -> bool {
        self.sources.is_empty()
    }

    /// The recorded sources.
    pub fn sources(&self) -> &[TaintSource] {
        &self.sources
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn union_is_idempotent() {
        let mut a = TaintSet::of(TaintSource::ModelOutput);
        a.add(TaintSource::ModelOutput);
        assert_eq!(a.sources().len(), 1);
        a.union(&TaintSet::of(TaintSource::ModelOutput));
        assert_eq!(a.sources().len(), 1);
    }

    #[test]
    fn protected_is_detected_through_union() {
        let vault = Path::parse("state://vault/alice/x").unwrap();
        let mut t = TaintSet::of(TaintSource::ModelOutput);
        assert!(!t.has_protected());
        t.union(&TaintSet::of(TaintSource::Protected { path: vault }));
        assert!(t.has_protected());
        assert!(t.has_untrusted_content());
    }

    #[test]
    fn pristine_has_no_taint() {
        let t = TaintSet::pristine();
        assert!(t.is_pristine());
        assert!(!t.has_protected());
        assert!(!t.has_untrusted_content());
    }

    #[test]
    fn author_constant_is_not_untrusted() {
        let t = TaintSet::author();
        assert!(!t.has_untrusted_content());
        assert!(!t.has_protected());
    }
}
