[package]
name = "nexus-state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true, default-features = false }
dashmap = { workspace = true, default-features = false }
nexus-types.workspace = true
parking_lot = { workspace = true, default-features = false }
serde_json = { workspace = true, default-features = false, features = ["std"] }
thiserror = { workspace = true, default-features = false, features = ["std"] }
tokio = { workspace = true, default-features = false, features = ["rt", "sync", "macros"] }

[dev-dependencies]
anyhow = { workspace = true, default-features = false, features = ["std"] }
criterion = { workspace = true, default-features = false, features = ["cargo_bench_support"] }
tokio = { workspace = true, default-features = false, features = ["rt", "sync", "macros", "time", "test-util"] }

[[bench]]
name = "in_memory_state"
harness = false
