//! Value provenance and taint tracking.
//!
//! A capability grant controls where a Process may act. Taint records where a
//! value's data came from: author constants, model output, inbound events,
//! fetched content, or protected sources. That lineage propagates
//! input-to-output through Operations, so policy can make later decisions from
//! provenance. For example, an outbound
//! Operation can be denied when its input lineage touched a `Protected` source.
//!
//! Boundary: taint is conservative. It can produce false positives. It records
//! whether protected lineage participated in producing a value.

use crate::path::Path;
use serde::{Deserialize, Serialize};
use smol_str::SmolStr;

/// Where a value's data originated. The lineage label that propagates with the
/// value through every Operation.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Ord, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaintSource {
    /// Hard-coded in the Program by its author. Trusted.
    AuthorConstant,
    /// Generated by a model (an inference Operation's output).
    ModelOutput,
    /// An external payload admitted by a daemon-owned ingress boundary, such as
    /// a gateway submission, Source event, object upload, or Provider result.
    /// The source and channel labels are assigned by the daemon; external
    /// self-reported provenance cannot clear or forge them.
    Inbound {
        /// Daemon-assigned ingress source, for example `gateway/default`,
        /// `source/<installation>/<projection>`, or `provider/endpoint/...`.
        source: SmolStr,
        /// Daemon-assigned ingress channel within that source.
        channel: SmolStr,
    },
    /// A fetch result or external tool output, tagged by host.
    Fetched {
        /// Host that produced the fetched content.
        host: SmolStr,
    },
    /// Read from a protected source (`state://vault/*`, private, health).
    Protected {
        /// Protected path that contributed data.
        path: Path,
    },
}

impl TaintSource {
    /// Whether this source is protected (vault / private / health). Outbound
    /// flow of protected data is structurally denied.
    pub fn is_protected(&self) -> bool {
        matches!(self, TaintSource::Protected { .. })
    }

    /// Whether this source is untrusted content (model / inbound / fetched) —
    /// the lineage that makes a value a memory-poisoning risk.
    pub fn is_untrusted_content(&self) -> bool {
        matches!(
            self,
            TaintSource::ModelOutput | TaintSource::Inbound { .. } | TaintSource::Fetched { .. }
        )
    }
}

/// The set of sources a value's lineage has touched. Empty = pristine
/// (equivalent to a pure author constant with nothing mixed in). The set is the
/// union of every input's taint that flowed into producing this value.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct TaintSet {
    sources: Vec<TaintSource>,
}

impl TaintSet {
    /// A pristine (empty) taint set.
    pub fn pristine() -> Self {
        Self {
            sources: Vec::new(),
        }
    }

    /// A taint set with a single source.
    pub fn of(source: TaintSource) -> Self {
        Self {
            sources: vec![source],
        }
    }

    /// Author-constant taint (trusted program literal).
    pub fn author() -> Self {
        Self::of(TaintSource::AuthorConstant)
    }

    /// Add a source (idempotent — duplicates are coalesced).
    pub fn add(&mut self, source: TaintSource) {
        if !self.sources.contains(&source) {
            self.sources.push(source);
        }
    }

    /// Union another set into this one. Output taint is the union of all input
    /// taints.
    pub fn union(&mut self, other: &TaintSet) {
        for s in &other.sources {
            self.add(s.clone());
        }
    }

    /// Merge two sets into a new one.
    pub fn merged(mut self, other: &TaintSet) -> Self {
        self.union(other);
        self
    }

    /// Whether the lineage touched any protected source.
    pub fn has_protected(&self) -> bool {
        self.sources.iter().any(TaintSource::is_protected)
    }

    /// Whether the lineage touched untrusted content (memory-poison gate).
    pub fn has_untrusted_content(&self) -> bool {
        self.sources.iter().any(TaintSource::is_untrusted_content)
    }

    /// Whether the set is pristine (no recorded sources).
    pub fn is_pristine(&self) -> bool {
        self.sources.is_empty()
    }

    /// The recorded sources.
    pub fn sources(&self) -> &[TaintSource] {
        &self.sources
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use anyhow::ensure;

    #[test]
    fn union_is_idempotent() {
        let mut a = TaintSet::of(TaintSource::ModelOutput);
        a.add(TaintSource::ModelOutput);
        assert_eq!(a.sources().len(), 1);
        a.union(&TaintSet::of(TaintSource::ModelOutput));
        assert_eq!(a.sources().len(), 1);
    }

    #[test]
    fn protected_is_detected_through_union() -> anyhow::Result<()> {
        let vault = Path::parse("state://vault/alice/x")?;
        let mut t = TaintSet::of(TaintSource::ModelOutput);
        ensure!(!t.has_protected(), "new model taint was protected");
        t.union(&TaintSet::of(TaintSource::Protected { path: vault }));
        ensure!(t.has_protected(), "protected taint was not detected");
        ensure!(t.has_untrusted_content(), "model taint was not preserved");
        Ok(())
    }

    #[test]
    fn pristine_has_no_taint() {
        let t = TaintSet::pristine();
        assert!(t.is_pristine());
        assert!(!t.has_protected());
        assert!(!t.has_untrusted_content());
    }

    #[test]
    fn author_constant_is_not_untrusted() {
        let t = TaintSet::author();
        assert!(!t.has_untrusted_content());
        assert!(!t.has_protected());
    }

    #[test]
    fn inbound_payload_is_untrusted() {
        let t = TaintSet::of(TaintSource::Inbound {
            source: "provider/endpoint/7/resource/11/method/0/binding/3".into(),
            channel: "effect://external-provider/acme/search".into(),
        });
        assert!(t.has_untrusted_content());
        assert!(!t.has_protected());
    }
}
