//! A narrow, host-managed invitation exchange. Redemption creates one exact
//! hosted-subject stream grant in the same durable transaction as consumption.

use aws_lc_rs::rand::{SecureRandom as _, SystemRandom};
use sha2::{Digest as _, Sha384};
use zeroize::Zeroize as _;

use crate::{
    Digest, FederationError, FederationNodeId, GrantHistory, HostedSubject, RequestId, StreamRef,
    SubjectGrantEntry,
};

/// Maximum invitation records retained by a store.
pub const MAX_INVITATIONS: usize = 4096;
/// Maximum exact issuer authorities retained by a store.
pub const MAX_INVITATION_ISSUERS: usize = 4096;
/// Maximum rows in one manifest reconciliation page.
pub const MAX_MANIFEST_PAGE: usize = 256;
/// Maximum successful uses allowed for one bearer invitation.
pub const MAX_INVITATION_REDEMPTIONS: u32 = 256;
/// Fixed replay-evidence retention after an invitation expires.
pub const INVITATION_RECEIPT_RETENTION_MS: u64 = 30 * 24 * 60 * 60 * 1000;
const SECRET_BYTES: usize = 32;
const SECRET_DOMAIN: &[u8] = b"xolotl.federation.invitation-secret.v1\0";

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
/// Provider-local invitation identity; IDs are never reused.
pub struct InvitationId([u8; 16]);

impl InvitationId {
    /// Big-endian, strictly increasing provider-local sequence. Its monotonic
    /// high-water mark survives receipt retirement, so an old ID cannot issue
    /// a new invitation after its evidence is pruned.
    pub const fn from_sequence(sequence: u128) -> Self {
        Self(sequence.to_be_bytes())
    }
    /// Construct an identity from its canonical 16-byte representation.
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }
    /// Return the canonical 16-byte identity.
    pub const fn as_bytes(self) -> [u8; 16] {
        self.0
    }
    /// Return the provider-local monotonic sequence number.
    pub const fn sequence(self) -> u128 {
        u128::from_be_bytes(self.0)
    }
}

/// A 256-bit bearer secret generated by the OS CSPRNG. Debug never prints it;
/// Each owned copy is erased on drop. Callers remain responsible for any
/// source buffer, wire framing, and transport allocation containing the secret.
#[derive(Clone, Eq, PartialEq)]
pub struct InvitationSecret([u8; SECRET_BYTES]);

impl core::fmt::Debug for InvitationSecret {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("InvitationSecret([redacted])")
    }
}

impl Drop for InvitationSecret {
    fn drop(&mut self) {
        self.0.zeroize();
    }
}

impl InvitationSecret {
    /// Generate a fresh bearer secret from the operating system RNG.
    pub fn generate() -> Result<Self, FederationError> {
        let mut bytes = [0; SECRET_BYTES];
        SystemRandom::new().fill(&mut bytes).map_err(|_error| {
            FederationError::Storage("invitation randomness unavailable".into())
        })?;
        Ok(Self(bytes))
    }

    /// Construct a secret from bytes owned by the caller.
    pub const fn from_bytes(bytes: [u8; SECRET_BYTES]) -> Self {
        Self(bytes)
    }
    /// Borrow the secret bytes for authenticated transport encoding.
    pub const fn as_bytes(&self) -> &[u8; SECRET_BYTES] {
        &self.0
    }

    /// Compute the domain-separated digest stored with a bearer invitation.
    pub fn digest(&self, id: InvitationId) -> Digest {
        let mut hasher = Sha384::new();
        hasher.update(SECRET_DOMAIN);
        hasher.update(id.as_bytes());
        hasher.update(self.0);
        Digest::from_bytes(hasher.finalize().into())
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Admission mode for an invitation redemption.
pub enum InvitationAudience {
    /// Only this holder and presenting node can redeem.
    Named {
        /// Authenticated node allowed to present the named holder.
        presenter: FederationNodeId,
        /// Exact hosted subject allowed to redeem this invitation.
        subject: HostedSubject,
    },
    /// A high-entropy secret may be exchanged by any holder admitted under the
    /// host's issuer/presenter/namespace policy. Every redemption is fixed to
    /// that holder's proven subject and presenter.
    Bearer {
        /// Domain-separated digest of the invitation ID and bearer secret.
        secret_digest: Digest,
    },
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Terms of one host-managed invitation and resulting stream grant.
pub struct InvitationSpec {
    /// Local share authority. Its exact stream revision is captured at create.
    pub issuer: HostedSubject,
    /// Exact locally published stream that will be granted.
    pub stream: StreamRef,
    /// Named or secret-bearing audience allowed to redeem.
    pub audience: InvitationAudience,
    /// Earliest redemption time, in Unix milliseconds.
    pub not_before_ms: u64,
    /// Last redemption time, in Unix milliseconds.
    pub expires_ms: u64,
    /// Expiry assigned to the resulting stream grant.
    pub grant_expires_ms: u64,
    /// Maximum successful redemption count.
    pub max_redemptions: u32,
    /// History scope assigned to the resulting stream grant.
    pub history: GrantHistory,
}

impl InvitationSpec {
    /// Validate identity, time bounds, publisher and audience terms.
    pub fn validate(
        &self,
        local_node: FederationNodeId,
        id: InvitationId,
    ) -> Result<(), FederationError> {
        if id.as_bytes() == [0; 16]
            || self.stream.publisher != local_node
            || self.not_before_ms >= self.expires_ms
            || self.grant_expires_ms <= self.not_before_ms
            || self.grant_expires_ms > self.expires_ms
            || self
                .expires_ms
                .checked_add(INVITATION_RECEIPT_RETENTION_MS)
                .is_none()
            || self.max_redemptions == 0
            || self.max_redemptions > MAX_INVITATION_REDEMPTIONS
            || !valid_subject(&self.issuer)
        {
            return Err(FederationError::Invalid("invalid invitation"));
        }
        match &self.audience {
            InvitationAudience::Named { presenter, subject } => {
                if *presenter == local_node || !valid_subject(subject) || self.max_redemptions != 1
                {
                    return Err(FederationError::Invalid(
                        "invalid named invitation audience",
                    ));
                }
            }
            InvitationAudience::Bearer { secret_digest } => {
                if secret_digest.as_bytes() == &[0; 48] {
                    return Err(FederationError::Invalid("invalid bearer secret digest"));
                }
            }
        }
        Ok(())
    }
}

fn valid_subject(subject: &HostedSubject) -> bool {
    [&subject.namespace, &subject.subject].iter().all(|value| {
        !value.is_empty() && value.len() <= 256 && !value.chars().any(char::is_control)
    })
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Current public state of one host-managed invitation.
pub struct InvitationView {
    /// Provider-local invitation identity.
    pub id: InvitationId,
    /// Immutable terms captured when the invitation was created.
    pub spec: InvitationSpec,
    /// Issuer authority revision captured at creation.
    pub issuer_authority_revision: u64,
    /// Revision used for conditional revocation or redemption.
    pub revision: u64,
    /// Whether new redemptions are currently enabled.
    pub enabled: bool,
    /// Number of successful redemptions already committed.
    pub redemptions: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Exact issuer and stream selected by management authority.
pub struct InvitationIssuerKey {
    /// Local hosted subject allowed to share the stream.
    pub issuer: HostedSubject,
    /// Exact stream covered by this authority.
    pub stream: StreamRef,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Current management decision for one issuer and stream.
pub struct InvitationIssuerAuthority {
    /// Exact issuer and stream governed by this decision.
    pub key: InvitationIssuerKey,
    /// Compare-and-swap revision of the decision.
    pub revision: u64,
    /// Whether the issuer may currently share this stream.
    pub enabled: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Authenticated request to redeem one invitation.
pub struct RedeemInvitationRequest {
    /// Invitation to consume.
    pub invitation: InvitationId,
    /// Stable redemption identity for idempotent retries.
    pub request_id: RequestId,
    /// Presenting node authenticated by the channel.
    pub authenticated_presenter: FederationNodeId,
    /// Hosted subject proven for this redemption.
    pub subject: HostedSubject,
    /// Invitation revision expected by the caller.
    pub expected_invitation_revision: u64,
    /// Bearer secret when the audience uses secret admission.
    pub secret: Option<InvitationSecret>,
    /// Trusted current time supplied by the host.
    pub now_ms: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
/// Durable receipt for a successful invitation redemption.
pub struct InvitationRedemption {
    /// Invitation that created the stream grant.
    pub invitation: InvitationId,
    /// Stable redemption request identity.
    pub request_id: RequestId,
    /// Authenticated node that presented the request.
    pub presenter: FederationNodeId,
    /// Hosted subject that received the exact stream grant.
    pub subject: HostedSubject,
    /// Grant created atomically with invitation consumption.
    pub grant: SubjectGrantEntry,
    /// Recomputed on inspection; an old receipt never revives revoked access.
    pub currently_authorized: bool,
}

/// Management can change an issuer's right to share one exact stream. Changing
/// the revision fences all invitations created under its earlier decision.
pub trait FederationInvitationStore: Send + Sync {
    /// Bind verified remote authority to each actual backend decision.
    /// Unsupported backends must reject, never substitute a preflight check.
    fn bind_invitation_decision(
        &self,
        _decision: crate::FederationDecision,
    ) -> Result<std::sync::Arc<dyn FederationInvitationStore>, crate::FederationError> {
        Err(crate::FederationError::Unauthorized)
    }
    /// Return the local host node owned by this store.
    fn local_node(&self) -> FederationNodeId;
    /// Return the durable high-water identity used to prevent ID reuse.
    fn invitation_high_water(&self) -> Result<InvitationId, FederationError>;
    /// Set exact issuer authority with compare-and-swap semantics.
    fn set_invitation_issuer_authority(
        &self,
        issuer: &HostedSubject,
        stream: StreamRef,
        expected_revision: Option<u64>,
        enabled: bool,
    ) -> Result<u64, FederationError>;
    /// Read the current revision and enabled state of exact issuer authority.
    fn invitation_issuer_authority(
        &self,
        issuer: &HostedSubject,
        stream: StreamRef,
    ) -> Result<Option<(u64, bool)>, FederationError>;
    /// Create or update manifest-owned issuer authority atomically. An
    /// embedding-owned row cannot be claimed by configuration reconciliation.
    fn set_manifest_invitation_issuer_authority(
        &self,
        issuer: &HostedSubject,
        stream: StreamRef,
        expected_revision: Option<u64>,
        enabled: bool,
    ) -> Result<u64, FederationError>;
    /// Page through manifest-owned issuer authorities by exact key.
    fn list_manifest_issuer_authorities(
        &self,
        after: Option<&InvitationIssuerKey>,
        limit: usize,
    ) -> Result<Vec<InvitationIssuerAuthority>, FederationError>;
    /// Create a host-owned invitation after checking current issuer authority.
    fn create_invitation(
        &self,
        id: InvitationId,
        spec: InvitationSpec,
        now_ms: u64,
    ) -> Result<InvitationView, FederationError>;
    /// Invitation and manifest ownership commit together. Plain creation
    /// retains embedding-host ownership and cannot later claim this row.
    fn create_manifest_invitation(
        &self,
        id: InvitationId,
        spec: InvitationSpec,
        now_ms: u64,
    ) -> Result<InvitationView, FederationError>;
    /// Page through manifest-owned invitations after an exclusive ID.
    fn list_manifest_invitations(
        &self,
        after: Option<InvitationId>,
        limit: usize,
    ) -> Result<Vec<InvitationView>, FederationError>;
    /// Read one invitation, including disabled invitations.
    fn invitation(&self, id: InvitationId) -> Result<Option<InvitationView>, FederationError>;
    /// Disable an invitation only at its expected revision.
    fn revoke_invitation(
        &self,
        id: InvitationId,
        expected_revision: u64,
    ) -> Result<InvitationView, FederationError>;
    /// Redeem and create the exact hosted-subject grant atomically.
    fn redeem_invitation(
        &self,
        request: RedeemInvitationRequest,
    ) -> Result<InvitationRedemption, FederationError>;
    /// Retire at most `limit` expired invitations once every possible grant is
    /// expired and receipts have been retained for the fixed replay window.
    /// A later retry for a retired ID reports an indeterminate old outcome;
    /// the persisted high-water mark forbids reissuing that ID.
    fn retire_expired_invitations(
        &self,
        now_ms: u64,
        limit: usize,
    ) -> Result<usize, FederationError>;
}
