use thiserror::Error;

use crate::FederationNodeId;

/// Unreused identity of one publisher-owned ordered view.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StreamId([u8; 16]);

impl StreamId {
    /// Restore a previously assigned stream identity from its wire bytes.
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Canonical bytes used in persisted and wire references.
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

/// Identity generated by the subscriber, unique within its own node.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SubscriptionId([u8; 16]);

impl SubscriptionId {
    /// Restore an ID assigned by the owning subscriber.
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Canonical bytes of this subscriber-local ID.
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

/// A stable control or publication attempt identity.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct RequestId([u8; 16]);

impl RequestId {
    /// Restore an idempotency key; the caller must ensure it is not reused for
    /// a different logical request within the relevant retention lifetime.
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(bytes)
    }

    /// Canonical bytes of this idempotency key.
    pub const fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

/// The v1 SHA-384 fingerprint of canonical, domain-separated record content.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Digest([u8; 48]);

impl Digest {
    /// SHA-384 output length in bytes.
    pub const LEN: usize = 48;

    /// Restore a digest computed by the contract's domain-separated hash.
    pub const fn from_bytes(bytes: [u8; 48]) -> Self {
        Self(bytes)
    }

    /// Canonical SHA-384 digest bytes.
    pub const fn as_bytes(&self) -> &[u8; 48] {
        &self.0
    }
}

/// Publisher-scoped identity of one immutable ordered export view.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct StreamRef {
    /// Node that assigns sequence numbers and owns the stream.
    pub publisher: FederationNodeId,
    /// Identifier unique within that publisher.
    pub id: StreamId,
}

/// Subscriber-scoped identity of one durable relationship to a stream.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SubscriptionRef {
    /// Node that selected the subscription ID and stores received records.
    pub subscriber: FederationNodeId,
    /// Identifier unique within that subscriber.
    pub id: SubscriptionId,
}

/// A positive position whose digest binds its complete immutable record.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Position {
    sequence: u64,
    digest: Digest,
}

impl Position {
    /// Construct a positive stream position with the exact record digest.
    pub fn new(sequence: u64, digest: Digest) -> Result<Self, FederationError> {
        if sequence == 0 {
            return Err(FederationError::Invalid(
                "position sequence must be positive",
            ));
        }
        Ok(Self { sequence, digest })
    }

    /// One-based sequence assigned by the stream's publisher.
    pub const fn sequence(self) -> u64 {
        self.sequence
    }

    /// Digest of the complete immutable record at this sequence.
    pub const fn digest(self) -> Digest {
        self.digest
    }

    pub(crate) const fn from_valid_record(sequence: u64, digest: Digest) -> Self {
        Self { sequence, digest }
    }
}

/// Revisions of two independent, locally owned authority decisions.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct AuthorityRevision {
    /// Revision of the local peer enablement decision.
    pub peer: u64,
    /// Revision of the peer's permission for the exact export.
    pub export: u64,
}

/// Directional permission for one peer and one export.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ExportAccess {
    /// This node may serve this export to the peer.
    pub serve: bool,
    /// This node may accept this export from the peer.
    pub receive: bool,
}

/// Local admission for an authenticated peer's online authorizations. This is
/// independent of export permission, so routine online-key rotation does not
/// change a subscription's content authority revision. An empty digest list
/// denies every online key until an operator installs a new revision.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PeerAdmission {
    /// Oldest online authorization generation accepted for this peer.
    pub minimum_online_generation: u64,
    /// SHA-384 digests of explicitly admitted online authorizations.
    pub allowed_authorization_digests: Vec<[u8; 48]>,
}

impl PeerAdmission {
    /// Maximum simultaneously admitted authorizations for one peer.
    pub const MAX_AUTHORIZATIONS: usize = 8;

    /// Reject zero generations, duplicate digests, or an oversized allowlist.
    pub fn validate(&self) -> Result<(), FederationError> {
        if self.minimum_online_generation == 0 {
            return Err(FederationError::Invalid(
                "minimum online generation must be positive",
            ));
        }
        if self.allowed_authorization_digests.len() > Self::MAX_AUTHORIZATIONS {
            return Err(FederationError::Capacity);
        }
        for (index, digest) in self.allowed_authorization_digests.iter().enumerate() {
            if self.allowed_authorization_digests[..index].contains(digest) {
                return Err(FederationError::Invalid(
                    "duplicate online authorization digest",
                ));
            }
        }
        Ok(())
    }
}

/// A stable, literal export name. It is not a local Path or authorization rule.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ExportName(String);

impl ExportName {
    /// Validate a nonempty printable name of at most 256 bytes.
    pub fn new(value: impl Into<String>) -> Result<Self, FederationError> {
        let value = value.into();
        if value.is_empty() || value.len() > 256 || value.chars().any(char::is_control) {
            return Err(FederationError::Invalid("invalid export name"));
        }
        Ok(Self(value))
    }

    /// Borrow this export's literal name.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Borrow its UTF-8 bytes for a canonical hash or storage key.
    pub fn as_bytes(&self) -> &[u8] {
        self.0.as_bytes()
    }
}

/// A known decision is distinct from a commit whose result cannot be proven.
#[derive(Clone, Debug, Eq, Error, PartialEq)]
pub enum FederationError {
    /// Input or returned data violates a local or wire contract. This error
    /// class alone says nothing about accepted work or its commit verdict;
    /// only the operation owner can prove a business commit did not occur.
    #[error("invalid federation input: {0}")]
    Invalid(&'static str),
    /// The current principal lacks permission for this exact operation.
    #[error("peer or export is not authorized")]
    Unauthorized,
    /// No item exists under the supplied stable identity.
    #[error("federation item does not exist")]
    NotFound,
    /// Immutable identity, content, or state conflicts with retained evidence.
    #[error("identity, revision or immutable content conflicts")]
    Conflict,
    /// A compare-and-set operation observed a different control revision.
    #[error("federation authority revision conflicts with expected revision")]
    RevisionConflict,
    /// A record skipped the next required sequence; the missing range must be read.
    #[error("expected sequence {expected}, received {received}")]
    Gap {
        /// Next expected sequence.
        expected: u64,
        /// Sequence supplied by the caller.
        received: u64,
    },
    /// Required history has been pruned and needs a supported resync contract.
    #[error("history is unavailable before sequence {minimum_available}")]
    ResyncRequired {
        /// Earliest sequence whose payload remains available.
        minimum_available: u64,
    },
    /// An explicit count or byte limit would be exceeded.
    #[error("federation capacity exceeded")]
    Capacity,
    /// The underlying effect may have committed; inspect retained evidence.
    #[error("commit outcome is indeterminate")]
    Indeterminate,
    /// Security time could not be retained; this decision's business changes
    /// were not committed. Stop operations that depend on trusted time.
    #[error("trusted federation time unavailable; business changes were not committed")]
    TrustedTimeUnavailable,
    /// The trusted local clock regressed across a security decision.
    #[error("trusted federation clock moved backwards")]
    ClockRollback,
    /// Persisted rows violate a required invariant; do not continue the stream.
    #[error("persisted federation state is corrupt")]
    Corrupt,
    /// Storage returned a concrete failure rather than a known domain result.
    #[error("federation storage failure: {0}")]
    Storage(String),
}
