[book]
title = "Xolotl 手册"
authors = ["noctiro"]
language = "zh-CN"
src = "src"

[output.html]
additional-css = ["theme/cjk.css"]
git-repository-url = "https://github.com/xolotl-org/xolotl"
edit-url-template = "https://github.com/xolotl-org/xolotl/edit/main/docs/zh-CN/{path}"
