[package]
name = "andrias-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
bitflags = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = ["derive", "std"] }
serde_json = { workspace = true, default-features = false, features = ["std"] }
smol_str = { workspace = true, default-features = false, features = ["serde", "std"] }
thiserror = { workspace = true, default-features = false, features = ["std"] }

[dev-dependencies]
anyhow = { workspace = true, default-features = false, features = ["std"] }
