[package]
name = "xolotl-plan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
xolotl-graph.workspace = true
xolotl-types.workspace = true
serde = { workspace = true, default-features = false, features = ["derive", "std"] }
serde_json = { workspace = true, default-features = false, features = ["std"] }
thiserror = { workspace = true, default-features = false, features = ["std"] }
yaml_serde = { workspace = true, default-features = false }

[dev-dependencies]
anyhow = { workspace = true, default-features = false, features = ["std"] }
