[package]
name = "nexus-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[features]
default = []
standard = ["dep:nexus-standard", "nexus-standard/standard"]

[dependencies]
nexus-standard = { workspace = true, default-features = false, optional = true }
nexus-graph.workspace = true
nexus-kernel.workspace = true
nexus-plan.workspace = true
nexus-state.workspace = true
nexus-types.workspace = true

[dev-dependencies]
anyhow = { workspace = true, default-features = false, features = ["std"] }
serde_json = { workspace = true, default-features = false, features = ["std"] }
tokio = { workspace = true, default-features = false, features = ["rt", "sync", "macros"] }
