[package]
name = "nexus-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
async-trait = "0.1.89"
blake3 = "1.8.5"
nexus-graph = { version = "0.1.0", path = "../nexus-graph" }
nexus-state = { version = "0.1.0", path = "../nexus-state" }
nexus-types = { version = "0.1.0", path = "../nexus-types" }
parking_lot = "0.12.5"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["rt", "sync", "macros", "time", "rt-multi-thread"] }
tracing = "0.1.44"
