[book]
title = "Xolotl Manual"
authors = ["noctiro"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/xolotl-org/xolotl"
edit-url-template = "https://github.com/xolotl-org/xolotl/edit/main/docs/{path}"
