[book]
title = "Andrias Manual"
authors = ["noctiro"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/andrias-dev/andrias"
edit-url-template = "https://github.com/andrias-dev/andrias/edit/main/docs/{path}"
